#https://www.youtube.com/watch?v=5s9pR9UUtAU&ab_channel=JavaTechie

spring:
  application:
    name: ELK-STACK-EXAMPLE

server:
  port: 9898

logging:
  file: D:/Configure-Stuff/Git/OWN_REPO/elk-stack-logging-example/elk-stack.log